Traceback (most recent call last):
  File "/Users/junaluzi/opt/anaconda3/envs/quant-econ-book/lib/python3.8/site-packages/jupyter_cache/executors/basic.py", line 152, in execute
    executenb(nb_bundle.nb, cwd=tmpdirname)
  File "/Users/junaluzi/opt/anaconda3/envs/quant-econ-book/lib/python3.8/site-packages/nbconvert/preprocessors/execute.py", line 737, in executenb
    return ep.preprocess(nb, resources, km=km)[0]
  File "/Users/junaluzi/opt/anaconda3/envs/quant-econ-book/lib/python3.8/site-packages/nbconvert/preprocessors/execute.py", line 405, in preprocess
    nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
  File "/Users/junaluzi/opt/anaconda3/envs/quant-econ-book/lib/python3.8/site-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "/Users/junaluzi/opt/anaconda3/envs/quant-econ-book/lib/python3.8/site-packages/nbconvert/preprocessors/execute.py", line 448, in preprocess_cell
    raise CellExecutionError.from_cell_and_msg(cell, out)
nbconvert.preprocessors.execute.CellExecutionError: An error occurred while executing the following cell:
------------------
'300' + 400
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-5-263a89d2d982>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0;34m'300'[0m [0;34m+[0m [0;36m400[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mTypeError[0m: can only concatenate str (not "int") to str
TypeError: can only concatenate str (not "int") to str

